name: CodeQL

on: [push, pull_request]

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  analyze:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
          languages: cpp, python
          queries: +security-and-quality
      - uses: github/codeql-action/autobuild@v2
      - uses: github/codeql-action/analyze@v2
      
